---
title: "Some notes on citation management in LaTeX"
author: "Wenxuan Jiang"
date: 02/18/2026
---

Recently I have been writing my first manuscript in LaTeX, and the time has come that I need to insert all the relevant papers I have been hoarding in Zotero to the .tex file. I thought it would just be as simple as exporting a .bib file from Zotero and placing it in the manuscript folder. But boy I was wrong, the .bib file that was generated by default had many unnecessary fields, e.g. abstract, file path, etc, and it didn't seem to give me an option in Zotero to unselect them when exporting. Also, there was I was baffled, so here I am, writing notes to answer some questions I had in the process.

### Q1: What is the difference between **bibtex**, **biblatex**, and **natbib** packages?

**BibTeX** is the processing engine for managing bibliography. Its counterpart is **Biber**, which is the processing engine used by **BibLaTex** ^[https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib]. **natbib** and **BibLaTex** are the LaTeX packages that control citation styles. Overleaf recommends the use of **BibLaTeX** since it is the modern solution for bibliography management in LaTeX, which handles unicode well and provides many styles. However, many journals still use *.bst* files for specifying references style for historical reasons and software stability (**natbib** and **BibTeX** are fairly stable after many years of development). This is important since only **natbib** with **BibTeX** engine can handle *.bst* files ^[https://www.overleaf.com/learn/latex/Bibliography_management_with_natbib#Adding_the_bibliography_in_the_table_of_contents].

Final verdict: we could stick with **natbib** and **BibTeX** when writing manuscript for the sake of complying with journals' reference style guide -- usually available with a *.bst* file.

### Q2: How to remove irrelevant fields in .bib files such as abstract, keywords, file?

We need to download the plugin **BetterBibTeX** for Zotero, then under Zotero preference $\rightarrow$ BetterBibTeX preference, enter the fileds not wanted.

### Little details:
- **BibTeX** doesn't recognize .bib files with space in its name